[pytest]
addopts = -s -v
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test*
markers=
    users: маркировка для тестов, связанных с пользователями.
    files: маркировка для тестов, связанных с файлами.
    regression: маркировка для регрессионных тестов.
    authentication: маркер для тестов, связанных с аутентификацией.